### ISSUE TITLE
Question: Is there a way to have a low level alarm?

### ISSUE THREAD

**Issue by ganar** [alaudet/raspi-sump#13]
Our needs are the opposite of the ones that you solved with your system: we need to know when the level of a big tank is too low (in this case a 10.000 L tank)

Do you think this can be easily changed in the code?

**Comment by alaudet** [comment]
The program allows you to measure for low water levels.  The setting to do this is in raspisump.conf.

Change 'alert_when = high'  to 'alert_when = low'

**Comment by ganar** [comment]
Thanks again for your help @alaudet

**Comment by alaudet** [comment]
It's my pleasure.  Hope you can make use of it to suit your needs.
