### ISSUE TITLE
Web page stopped working

### ISSUE THREAD

**Issue by rescuemoe** [alaudet/raspi-sump#42]
I think I may be missing something here 
I just upgraded to the new version by running 
sudo pip3 install -U raspisump
now when I go to the ip address of my pi to show the graph I get page not found
Was there other things that needed to get upgraded?
Thanks

**Comment by alaudet** [comment]
Nothing has changed.

Try running with the option --no-binary :all: after the -U

**Comment by rescuemoe** [comment]
Thanks that solved 
Thanks for the upgrade!!

**Comment by rescuemoe** [comment]
Actually it did not solve it gota loves windows I get page not found on my windows 7 machine but it works fine on my android phone. rrrrr
