### ISSUE TITLE
trigger additional scripts when threshold is reached

### ISSUE THREAD

**Issue by veeectorm** [alaudet/raspi-sump#48]
I wanted to ask if there is any way to trigger an additional script when the threshold is reached. I wanted to use pushbullet or pushover to send a push notification on top of the existing SMS/Email notif.

THanks!

**Comment by alaudet** [comment]
Sure, in reading.py

```
if water_depth > critical_water_level and configs['alert_when'] == 'high':
    alerts.determine_if_alert(water_depth)
    *** do other stuff ***
```
