### ISSUE TITLE
Higher resolution graphic for wiring diagram?

### ISSUE THREAD

**Issue by geerlingguy** [alaudet/raspi-sump#60]
I am currently working on getting the parts together to build this project (my old sump pump died a couple weeks ago, and I'm glad I heard it making a motor-burning-out noise or else my basement would've flooded this week since we've had a lot of precipitation!).

While looking through the documentation, I am impressed by the overall quality (thanks, and I can tell you've put a lot into this project!), but one thing that was a little difficult was reading the wiring diagram on this page: https://www.linuxnorth.org/raspi-sump/ — see below:

![raspi-sump-wiring](https://user-images.githubusercontent.com/481677/72754219-d5675280-3b8c-11ea-95fa-1e39f9a00e7d.jpg)

If possible, could you export a 2 or 4x larger version, and either embed that in the page (so those with retina displays can immediately benefit), or link the image to the full res version, so it is easier to see the exact pin designations?

It's already good enough for me to be able to build based on the pin locations, but it would be even easier if I could read the labels like Gnd, Echo, Trig, Vcc, etc.

**Comment by alaudet** [comment]
I did this in Visio a long time ago.  I'll see what I can do.

**Comment by alaudet** [comment]
I don't have visio anymore to modify this.  I would be happy to change the image if someone contributed a more readable version.
thanks.

**Comment by alaudet** [comment]
Is this easier to read?

![hcsr04-diagram](https://user-images.githubusercontent.com/7563639/80220391-bc4dc200-8611-11ea-8495-63d3ca725b6b.JPG)

**Comment by geerlingguy** [comment]
@alaudet - Beautiful! I don't have to squint at all now.

**Comment by alaudet** [comment]
Not without making the HCSR04 picture bigger but I labelled each wire with the corresponding label on the sensor.

**Comment by alaudet** [comment]
Website updated with clearer diagram

**Comment by alaudet** [comment]
Thanks for the feedback...sorry it took so long.  :-)

**Comment by geerlingguy** [comment]
@alaudet - Would it surprise you to know that I've had the HC-SR04 sitting on my desk about 6" from my keyboard for a couple months now? I finished putting together three of the wires but was missing a crimp-on connector for the fourth, so I ordered a bunch. They arrived, I put the box on the other side of my desk, and it's all just sitting there staring at me every day asking "when you going to monitor your sump pit!?"

It happens 😆

**Comment by alaudet** [comment]
All this social distancing is giving people time to do these types of this.   :)
