### ISSUE TITLE
Spurious Peaks 

### ISSUE THREAD

**Issue by nickw56** [alaudet/raspi-sump#65]
I am getting occasional peak readings which seem to occur in the early hours of the morning. The sensor is mounted in a pipe which does not reach right to the bottom of the sump.  We have not had much rain for the last month and the the sump is empty:  I have attached some samples showing this behaviour;  

Any help you can provide to help me find the cause of this spike would be great.

![20200420](https://user-images.githubusercontent.com/37964325/80319237-5d519e00-8807-11ea-8f61-0938c8d6ad60.png)

![20200424](https://user-images.githubusercontent.com/37964325/80319191-15327b80-8807-11ea-9751-52caee229fcb.png)
 
![20200422](https://user-images.githubusercontent.com/37964325/80319200-1ebbe380-8807-11ea-8c7b-aa24ba13854e.png)

**Comment by nickw56** [comment]
Is anyone else experiencing this issue?  I have changed the sensor and it's still happening now and again.  I am certain it's not caused by the water level changing because the spike is very short (one reading) and the water level could not rise or fall that quickly.  
![rsump11062020](https://user-images.githubusercontent.com/37964325/84380867-03067400-abe0-11ea-93d9-4eba6129e9a6.JPG)

**Comment by nickw56** [comment]
sorry closed in error

**Comment by alaudet** [comment]
That is really strange, pretty consistent in the morning too.  I am not sure where to even start with that.

**Comment by KevinBott** [comment]
@nickw56  Can you correlate any other activity on the Pi at this time?  Anything in Cron, etc?  I'm wondering if something else is hogging the CPU at that time.

**Comment by alaudet** [comment]
This issue is now over 6 months old.  The originator can open a new request if this is still an issue.  @KevinBott  thanks for digging through old issues.  :-)
